// src/app/(legal)/privacy-policy/page.tsx
import type { Metadata } from "next";
import Link from "next/link";
import type { ReactNode } from "react";

import WrapperSmall from "@component/layout/WrapperSmall";
import H1 from "@component/typography/H1";
import H2 from "@component/typography/H2";
import H3 from "@component/typography/H3";
import H4 from "@component/typography/H4";

import { getDictionary } from "@util/server/translation";

export async function generateMetadata(): Promise<Metadata> {
    const trans = await getDictionary("privacy");
    return {
        title: `${trans.title} - Grizzl`,
    };
}

function P({ children }: { children: ReactNode }) {
    return <p className="mb-4">{children}</p>;
}

export default async function Page() {
    const trans = await getDictionary("privacy");
    const { phone, email } = await getDictionary("legal");
    return (
        <WrapperSmall>
            <div className="py-24">
                <div className="mb-8">
                    <H1>{trans.title}</H1>
                </div>
                <H2>{trans.section1Title}</H2>
                <H3>{trans.section1GeneralInfo}</H3>
                <P>{trans.section1GeneralInfoText}</P>
                <H3>{trans.section1DataCollection}</H3>
                <H4>{trans.section1Responsible}</H4>
                <P>{trans.section1ResponsibleText}</P>
                <H4>{trans.section1HowCollect}</H4>
                <P>{trans.section1HowCollectText1}</P>
                <P>{trans.section1HowCollectText2}</P>
                <H4>{trans.section1Use}</H4>
                <P>{trans.section1UseText}</P>
                <H4>{trans.section1Rights}</H4>
                <P>{trans.section1RightsText1}</P>
                <P>{trans.section1RightsText2}</P>
                <H2>{trans.section2Title}</H2>
                <P>{trans.section2HostingIntro}</P>
                <H3>Strato</H3>
                <P>{trans.section2HostingText1}</P>
                <P>
                    {trans.section2HostingText2}
                    <Link
                        href="https://www.strato.de/datenschutz/"
                        target="_blank"
                        className="inline-link-1 underline"
                        rel="noopener noreferrer"
                    >
                        https://www.strato.de/datenschutz/
                    </Link>
                    .
                </P>
                <P>{trans.section2HostingText3}</P>
                <H4>{trans.section2OrderProcessing}</H4>
                <P>{trans.section2OrderProcessingText}</P>
                <H2>{trans.section3Title}</H2>
                <H3>{trans.section3DataProtection}</H3>
                <P>{trans.section3DataProtectionText1}</P>
                <P>{trans.section3DataProtectionText2}</P>
                <P>{trans.section3DataProtectionText3}</P>
                <H3>{trans.section3ResponsibleNotice}</H3>
                <P>{trans.section3ResponsibleNoticeText1}</P>
                <P>
                    {process.env.LEGAL_RESPONSIBLE_ENTITY}
                    <br />
                    {process.env.LEGAL_STREET}
                    <br />
                    {process.env.LEGAL_ZIP_AND_CITY}
                </P>
                <P>
                    {phone}: {process.env.LEGAL_PHONE}
                    <br />
                    {email}:{" "}
                    <Link href={`mailto:${process.env.LEGAL_EMAIL}`} className="inline-link-1 underline">
                        {process.env.LEGAL_EMAIL}
                    </Link>
                    <br />
                </P>
                <P>{trans.section3ResponsibleNoticeText2}</P>
                <H3>{trans.section3StorageDuration}</H3>
                <P>{trans.section3StorageDurationText}</P>
                <H3>{trans.section3LegalBases}</H3>
                <P>{trans.section3LegalBasesText}</P>
                <H3>{trans.section3Recipients}</H3>
                <P>{trans.section3RecipientsText}</P>
                <H3>{trans.section3Revocation}</H3>
                <P>{trans.section3RevocationText}</P>
                <H3>{trans.section3RightToObject}</H3>
                <P>{trans.section3RightToObjectText1}</P>
                <P>{trans.section3RightToObjectText2}</P>
                <H3>{trans.section3Complaint}</H3>
                <P>{trans.section3ComplaintText}</P>
                <H3>{trans.section3Portability}</H3>
                <P>{trans.section3PortabilityText}</P>
                <H3>{trans.section3Encryption}</H3>
                <P>{trans.section3EncryptionText1}</P>
                <P>{trans.section3EncryptionText2}</P>
                <H3>{trans.section3PaymentEncryption}</H3>
                <P>{trans.section3PaymentEncryptionText1}</P>
                <P>{trans.section3PaymentEncryptionText2}</P>
                <P>{trans.section3PaymentEncryptionText3}</P>
                <H3>{trans.section3InformationRights}</H3>
                <P>{trans.section3InformationRightsText}</P>
                <H3>{trans.section3Restriction}</H3>
                <P>{trans.section3RestrictionText1}</P>
                <ul>
                    <li>{trans.section3RestrictionList1}</li>
                    <li>{trans.section3RestrictionList2}</li>
                    <li>{trans.section3RestrictionList3}</li>
                    <li>{trans.section3RestrictionList4}</li>
                </ul>
                <P>{trans.section3RestrictionText2}</P>
            </div>
        </WrapperSmall>
    );
}

// app/pages/privacy-policy.vue
<script setup lang="ts">
const runtimeConfig = useRuntimeConfig();
definePageMeta({
    title: "privacy.title",
});
</script>

<template>
    <LayoutWrapper>
        <div class="py-24">
            <div class="mb-8">
                <TypoH1>{{ $t("privacy.title") }}</TypoH1>
            </div>

            <TypoH2>{{ $t("privacy.section1Title") }}</TypoH2>

            <TypoH3>{{ $t("privacy.section1GeneralInfo") }}</TypoH3>
            <p class="mb-4">{{ $t("privacy.section1GeneralInfoText") }}</p>

            <TypoH3>{{ $t("privacy.section1DataCollection") }}</TypoH3>

            <TypoH4>{{ $t("privacy.section1Responsible") }}</TypoH4>
            <p class="mb-4">{{ $t("privacy.section1ResponsibleText") }}</p>

            <TypoH4>{{ $t("privacy.section1HowCollect") }}</TypoH4>
            <p class="mb-4">{{ $t("privacy.section1HowCollectText1") }}</p>
            <p class="mb-4">{{ $t("privacy.section1HowCollectText2") }}</p>

            <TypoH4>{{ $t("privacy.section1Use") }}</TypoH4>
            <p class="mb-4">{{ $t("privacy.section1UseText") }}</p>

            <TypoH4>{{ $t("privacy.section1Rights") }}</TypoH4>
            <p class="mb-4">{{ $t("privacy.section1RightsText1") }}</p>
            <p class="mb-4">{{ $t("privacy.section1RightsText2") }}</p>

            <TypoH2>{{ $t("privacy.section2Title") }}</TypoH2>
            <p class="mb-4">{{ $t("privacy.section2HostingIntro") }}</p>

            <TypoH3>Strato</TypoH3>
            <p class="mb-4">{{ $t("privacy.section2HostingText1") }}</p>

            <p class="mb-4">
                {{ $t("privacy.section2HostingText2") }}
                <NuxtLink
                    href="https://www.strato.de/datenschutz/"
                    target="_blank"
                    rel="noopener noreferrer"
                    class="inline-link-1 underline"
                >
                    https://www.strato.de/datenschutz/ </NuxtLink
                >.
            </p>

            <p class="mb-4">{{ $t("privacy.section2HostingText3") }}</p>

            <TypoH4>{{ $t("privacy.section2OrderProcessing") }}</TypoH4>
            <p class="mb-4">{{ $t("privacy.section2OrderProcessingText") }}</p>

            <TypoH2>{{ $t("privacy.section3Title") }}</TypoH2>

            <TypoH3>{{ $t("privacy.section3DataProtection") }}</TypoH3>
            <p class="mb-4">{{ $t("privacy.section3DataProtectionText1") }}</p>
            <p class="mb-4">{{ $t("privacy.section3DataProtectionText2") }}</p>
            <p class="mb-4">{{ $t("privacy.section3DataProtectionText3") }}</p>

            <TypoH3>{{ $t("privacy.section3ResponsibleNotice") }}</TypoH3>
            <p class="mb-4">{{ $t("privacy.section3ResponsibleNoticeText1") }}</p>

            <p class="mb-4">
                {{ runtimeConfig.public.legalEntity }}<br />
                {{ runtimeConfig.public.legalStreet }}<br />
                {{ runtimeConfig.public.legalCity }}
            </p>

            <p class="mb-4">
                {{ $t("legal.phone") }}: {{ runtimeConfig.public.legalPhone }}<br />
                {{ $t("legal.email") }}:
                <NuxtLink :href="`mailto:${runtimeConfig.public.legalEmail}`" class="inline-link-1 underline">
                    {{ runtimeConfig.public.legalEmail }}
                </NuxtLink>
                <br />
            </p>

            <p class="mb-4">{{ $t("privacy.section3ResponsibleNoticeText2") }}</p>

            <TypoH3>{{ $t("privacy.section3StorageDuration") }}</TypoH3>
            <p class="mb-4">{{ $t("privacy.section3StorageDurationText") }}</p>

            <TypoH3>{{ $t("privacy.section3LegalBases") }}</TypoH3>
            <p class="mb-4">{{ $t("privacy.section3LegalBasesText") }}</p>

            <TypoH3>{{ $t("privacy.section3Recipients") }}</TypoH3>
            <p class="mb-4">{{ $t("privacy.section3RecipientsText") }}</p>

            <TypoH3>{{ $t("privacy.section3Revocation") }}</TypoH3>
            <p class="mb-4">{{ $t("privacy.section3RevocationText") }}</p>

            <TypoH3>{{ $t("privacy.section3RightToObject") }}</TypoH3>
            <p class="mb-4">{{ $t("privacy.section3RightToObjectText1") }}</p>
            <p class="mb-4">{{ $t("privacy.section3RightToObjectText2") }}</p>

            <TypoH3>{{ $t("privacy.section3Complaint") }}</TypoH3>
            <p class="mb-4">{{ $t("privacy.section3ComplaintText") }}</p>

            <TypoH3>{{ $t("privacy.section3Portability") }}</TypoH3>
            <p class="mb-4">{{ $t("privacy.section3PortabilityText") }}</p>

            <TypoH3>{{ $t("privacy.section3Encryption") }}</TypoH3>
            <p class="mb-4">{{ $t("privacy.section3EncryptionText1") }}</p>
            <p class="mb-4">{{ $t("privacy.section3EncryptionText2") }}</p>

            <TypoH3>{{ $t("privacy.section3PaymentEncryption") }}</TypoH3>
            <p class="mb-4">{{ $t("privacy.section3PaymentEncryptionText1") }}</p>
            <p class="mb-4">{{ $t("privacy.section3PaymentEncryptionText2") }}</p>
            <p class="mb-4">{{ $t("privacy.section3PaymentEncryptionText3") }}</p>

            <TypoH3>{{ $t("privacy.section3InformationRights") }}</TypoH3>
            <p class="mb-4">{{ $t("privacy.section3InformationRightsText") }}</p>

            <TypoH3>{{ $t("privacy.section3Restriction") }}</TypoH3>
            <p class="mb-4">{{ $t("privacy.section3RestrictionText1") }}</p>

            <ul>
                <li>{{ $t("privacy.section3RestrictionList1") }}</li>
                <li>{{ $t("privacy.section3RestrictionList2") }}</li>
                <li>{{ $t("privacy.section3RestrictionList3") }}</li>
                <li>{{ $t("privacy.section3RestrictionList4") }}</li>
            </ul>

            <p class="mb-4">{{ $t("privacy.section3RestrictionText2") }}</p>
        </div>
    </LayoutWrapper>
</template>
