// src/component/navigation/BlockLink.tsx
import { clsx } from "clsx";
import Link from "next/link";
import type { ElementType, ReactNode } from "react";

import ArrowRight from "@component/icon/ArrowRight";

export default function BlockLink({
    children,
    color,
    onClick,
    href,
    "as": Component = Link,
    "data-test-id": id,
}: {
    "children": ReactNode;
    "color": string;
    "onClick"?: () => void;
    "href"?: string;
    "as"?: ElementType;
    "data-test-id"?: string;
}) {
    const hoverClass = clsx("absolute", "h-full", "w-full", "px-8", "py-3", "left-0", "top-full", color);
    if (Component === Link && !href) throw new Error("Component needs an href attribute");
    return (
        <Component
            onClick={onClick}
            data-test-id={id}
            href={Component === Link ? href : undefined}
            className="group relative flex h-full w-full justify-center gap-4 overflow-hidden rounded-full text-back"
        >
            <span className="w-full transition-transform group-hover:-translate-y-full group-focus-visible:-translate-y-full">
                <span className="flex h-full w-full items-center justify-center gap-2 bg-front px-8 py-3 text-center">
                    {children}
                </span>
                <span className={hoverClass}>
                    <ArrowRight className="absolute top-1/2 left-1/2 h-8 w-8 -translate-1/2 stroke-theme-white" />
                </span>
            </span>
        </Component>
    );
}

// app/core/components/nav/BlockLink.vue
<script setup lang="ts">
import { NuxtLink } from "#components";
import { ICON_ARROW_RIGHT } from "~/core/constants/icons.constant";

const {
    as = NuxtLink,
    disabled = false,
    dataTestId = undefined,
    to = undefined,
} = defineProps<{ as?: string | object; disabled?: boolean; dataTestId?: string; to?: string }>();
</script>

<template>
    <div class="relative">
        <component
            :is="disabled ? 'span' : as"
            :data-test-id="dataTestId"
            :to="disabled ? null : to"
            class="group relative flex h-full w-full justify-center gap-4 overflow-hidden rounded-full text-back select-none"
            :aria-hidden="disabled || null"
        >
            <span
                class="w-full transition-transform"
                :class="{
                    'group-hover:-translate-y-full group-focus-visible:-translate-y-full': !disabled,
                }"
            >
                <span
                    class="flex h-full w-full items-center justify-center gap-2 px-8 py-3 text-center text-nowrap"
                    :class="disabled ? 'bg-front text-neutral-400' : 'bg-front'"
                >
                    <slot />
                </span>
                <span class="absolute top-full left-0 h-full w-full bg-theme-dark px-8 py-3">
                    <UIcon
                        :name="ICON_ARROW_RIGHT"
                        class="absolute top-1/2 left-1/2 h-8 w-8 -translate-1/2 text-theme-white"
                    />
                </span>
            </span>
        </component>
        <span
            v-if="disabled"
            data-test-id="block-link-coming-soon"
            class="absolute top-0 -left-4 -translate-y-1/2 -rotate-5 rounded-full bg-error px-4 py-1 text-sm whitespace-nowrap text-theme-white"
        >
            {{ $t("menu.comingSoon") }}
        </span>
    </div>
</template>
