// src/components/navigation/Footer.tsx
import Link from "next/link";

export function Footer() {
    return (
        <footer className="h-footer-height">
            <nav className="flex h-full items-center justify-center gap-8">
                <Link className="inline-link-1" href="/legal-notice">
                    Legal Notice
                </Link>
                <Link className="inline-link-2" href="/privacy-policy">
                    Privacy Policy
                </Link>
                <Link className="inline-link-3" href="https://github.com/konstantin-lukas/grizzl.io">
                    Version 0.1.0
                </Link>
            </nav>
        </footer>
    );
}

// app/core/components/nav/Footer.vue
<template>
    <div class="relative" data-test-id="inert-elements">
        <footer class="absolute -top-footer-height h-footer-height w-full">
            <nav class="flex h-full w-full items-center justify-center gap-4 px-4 xs:justify-start sm:gap-8">
                <NuxtLink class="inline-link" to="/legal-notice" data-test-id="legal-notice-link">
                    {{ $t("footer.legalNotice") }}
                </NuxtLink>
                <NuxtLink class="inline-link" to="/privacy-policy" data-test-id="privacy-policy-link">
                    {{ $t("footer.privacyPolicy") }}
                </NuxtLink>
            </nav>
        </footer>
    </div>
</template>
